version: "3.8"
services:
  app:
    depends_on:
      - database
    container_name: nodejs2024q1-service
    image: viktorvinitski1/nodejs2024q1-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: always
    networks:
      - service_network
    command: npm run docker

  database:
    container_name: nodejs2024q1-service-database
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./logs:/logs
    networks:
      - service_network
    
volumes:
  postgres:
  logs:

networks:
  service_network: